/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 buc.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF,  useTexture,PivotControls,  Decal,} from '@react-three/drei'
import { applyProps, useFrame } from '@react-three/fiber'
import * as THREE from 'three'


const lookAtPos = new THREE.Vector3()
export function Model(props) {
  const { nodes, materials } = useGLTF('/buc-transformed.glb')

  const {decalsPosition: {decal1X,decal1Y,decal1Z,decal2X,decal2Y,decal2Z},} = props
  const decal1 = useTexture('/decals/decal1.png')
  const decal2 = useTexture('/decals/decal2.jpg')


  console.log("props.decalsPosition",props.decalsPosition)
  useFrame((state, delta) => {
    // const step = 0.1
    // state.camera.fov = THREE.MathUtils.lerp(state.camera.fov, zoom ? 10 : 42, step)
    // state.camera.position.lerp(dummy.set(zoom ? 25 : 10, zoom ? 1 : 5, zoom ? 0 : 10), step)

    // lookAtPos.x = Math.sin(state.clock.getElapsedTime() * 2)
    lookAtPos.y = 20

    state.camera.lookAt(lookAtPos)
    state.camera.updateProjectionMatrix()
  })

  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38.geometry} material={materials.plastic} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38001.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38002.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38003.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38004.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38005.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38006.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38007.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38008.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38009.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38010.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38011.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38012.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38013.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38014.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38015.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38016.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38017.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38018.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38019.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38020.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38021.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38022.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38023.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38024.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38025.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38026.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38027.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38028.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38029.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38030.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38031.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38032.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38033.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38034.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38041.geometry} material={materials.plastic} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38042.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38043.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38044.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38045.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38046.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38047.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38048.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38049.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38050.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38051.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38052.geometry} material={materials.gum} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38058.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38059.geometry} material={materials.alu_side} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38060.geometry} material={materials.alu} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38062.geometry} material={materials['chrome brushed']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38063.geometry} material={materials['chrome brushed']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38064.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38065.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38066.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38067.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38069.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38070.geometry} material={materials.gum} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38071.geometry} material={materials.gum} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38072.geometry} material={materials['chrome glosy']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38073.geometry} material={materials['chrome glosy']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38074.geometry} material={materials['chrome glosy']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38075.geometry} material={materials.gum} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38076.geometry} material={materials.gum} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38077.geometry} material={materials['chrome glosy']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38078.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38079.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38080.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38081.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38082.geometry} material={materials['Opaque(254,254,255).004']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38090.geometry} material={materials['Brushed Aluminum']} scale={0.4} />
      <mesh geometry={nodes.BUCv3_v41_simplified_jig_v38091.geometry} material={materials['chrome brushed']} scale={0.4} />
      <mesh geometry={nodes.frame.geometry} material={materials['Material.002']} scale={0.4} >
    
      <Decal debug  position={[decal1X, decal1Y, decal1Z]} rotation={0} scale={100} map={decal1} map-anisotropy={16} />
    
      <Decal debug position={[decal2X, decal2Y, decal2Z]} rotation={0} scale={100} map={decal2} map-anisotropy={16} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/buc-transformed.glb')
